# Generated by Django 5.1.2 on 2024-11-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleados', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('curp', models.CharField(max_length=18)),
                ('telefono', models.IntegerField()),
                ('horario', models.TimeField()),
                ('paga', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
