# Generated by Django 5.1.2 on 2024-11-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateTimeField()),
                ('estado_producto', models.CharField(max_length=30)),
                ('codigo_barras', models.IntegerField()),
                ('cantidad_stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
