# Generated by Django 5.1.2 on 2024-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_surcursal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=30)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('capacidad', models.IntegerField()),
                ('gerente', models.CharField(max_length=30)),
                ('horario', models.TimeField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
